//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi___FABIAN.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class activos
    {
        public int id_activo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string tipo { get; set; }
        public string serial { get; set; }
        public string num_inventario { get; set; }
        public string peso { get; set; }
        public string ancho { get; set; }
        public string alto { get; set; }
        public string largo { get; set; }
        public Nullable<double> valor_compra { get; set; }
        public System.DateTime fecha_compra { get; set; }
        public System.DateTime fecha_baja { get; set; }
        public string estado { get; set; }
        public string color { get; set; }
        public Nullable<int> id_area { get; set; }
        public Nullable<int> id_persona { get; set; }
    }
}
