//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi___FABIAN.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class personas
    {
        public int id_persona { get; set; }
        public string nombre { get; set; }
        public string genero { get; set; }
        public string telefono { get; set; }
    }
}
